Parameters:
  Username:
    Type: String
    NoEcho: True
  Password:
    Type: String
    NoEcho: True
Resources:

  MyRDSSecret:
    Type: AWS::SecretsManager::Secret
    Properties: 
      Description: 'Secret for my db'
      Name: 'MySecret'
      SecretString: !Sub '{"username":"${Username}","password": "${Password}"}'